### PR TITLE
Update Winapp2.ini

### PR DESCRIPTION
**Pull request by decofona**
[MSI Remind Manager *]
- New Entry

[Adobe Creative Cloud Experience *]
-New Entry

[LibreOffice *]
-FileKey 6 has been added.

[Adobe CC *]
-Detect2 has been added, since it wasn't recognized.

[Windows Energy Report *]
-New Entry

[SteelSeries *]
- New Added

[DSDCS InputMapper *]
- New Added

[JDownloader2 *]
- Actually JDownloader 2.0 will by defaul install into LocalAppData. 
- But I don't know, if earlier versions distributed had a different path.
- So both have been added.
- Also added output.log and install4.j.logs

[Atheros Driver *]
-Changed Detect, since it was not recognizing and added Installog.txt (FileKey3)

### CODE REVIEW

**Comment by decofona** [comment]
Also changed some of the "\|" with "\", since it's the same.

**Comment by APMichael** [comment]
Thank you for your suggestions.

Please do not change the ExcludeKeys. We use the official CCleaner syntax: "\\|". (By the way, using only the pipe symbol "|" did not work in the past.)

Please use for "%ProgramFiles%\\Common Files\\" the variable %CommonProgramFiles%.

The file "energy-report-latest.xml" you want to delete is a deliberately excluded file in the entry [Power Efficiency Diagnostics \*]. Therefore the new entry [Windows Energy Report \*] is not required.

And please always use Winapp2ool > WinappDebug to make sure the syntax and sorting is correct before opening a new pull request. Thank you very much.

**Comment by decofona** [comment]
As for using "\|" i was confused. I know, that excludekeys only have the path, no pipe.
But even then, what is more correct?

ExcludeKey1=FILE|%LocalAppData%\Microsoft\Windows\INetCache\IE\|container.dat

or

ExcludeKey1=FILE|%LocalAppData%\Microsoft\Windows\INetCache\IE|container.dat

**Comment by APMichael** [comment]
There is no "more correct". The official CCleaner syntax is always "\\|". Please read the README.md. Thanks.

ExcludeKey1=FILE|%LocalAppData%\\Microsoft\\Windows\\INetCache\\IE\\|container.dat

**Comment by decofona** [comment]
Closed in favor of new edit.

**Pull request closed without merging**
