### PR TITLE
Serious Sam

### PR DESCRIPTION
**Pull request by APMichael**
Suggestion for merging Serious Sam entries.

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
I think we can remove DetectFile 1 and 2 as I don't think those are really necessary.

**Comment by MoscaDotTo** [comment]
DetectFile1 might be, since it seems to be the non-steam link. DetectFile2 should be covered by one of the Detects though.

**Comment by ROCKNROLLKID** [comment]
Ah yes, I forgot these games have GOG copies, too. I retract my last request.

**Comment by APMichael** [comment]
Yes, DetectFile1 seems to be necessary for the non-steam version. But we can remove DetectFile2 because it refers to Steam only.

**Comment by ROCKNROLLKID** [comment]
@APMichael Do you know how to edit a PR?

**Comment by APMichael** [comment]
Sorry, I don't know how to edit a pull request. It seems that it isn't possible using the web interface?!

I submitted a revised pull request (#156). You can close this one. Thanks!

**Pull request closed without merging**
