### PR TITLE
Add moonlight entry

### PR DESCRIPTION
**Pull request by reloxx13**
Remove logs, cached box covers, support normal and portable mode

https://github.com/moonlight-stream/moonlight-qt

### CODE REVIEW

**Comment by APMichael** [comment]
Thanks for the new entry.
```
FileKey3=%LocalAppData%\Moonlight Game Streaming Project\Moonlight\cache\boxart\*
FileKey6=%ProgramFiles%\Moonlight Game Streaming\boxart\*
```
Please use the official syntax, so that it is always clear what the FileKey should delete:
```
...\boxart|*.*|RECURSE
```

**Comment by APMichael** [comment]
Thank you! 👍

**Comment by reloxx13** [comment]
WAIT

**Comment by reloxx13** [comment]
Heya,

I had it in Games section before but wanted to position it next to Parsec as both are the same type of app.

 It's not folder recursive. In box art are just different game cover images.


How would it be correct?

`C:\Program Files\Moonlight Game Streaming\boxart\e08a8ca2-2173-4189-a073-jnjhbnkj\32847.png`

I don't want to delete the last folder, as it's connected to the server identification. Just the images inside.

`\Moonlight\cache\boxart\*|*.*`   ? Without Trailing slash?

**Comment by APMichael** [comment]
Right, if you only want to delete the contents of a subfolder, but not the subfolder itself, then your FileKey is correct.

`...\boxart\*|*.*`

**Pull request merged**
