### PR TITLE
Update Winapp3.ini

### PR DESCRIPTION
**Pull request by decofona**
[Useless File Extension*]

-Added much more ExcludeKeys, so it won't find important or undeleteable files.

[Windows LCU *]

- This will clean the Windows LCU Folder, which is grown since some updates and it's not getting cleaned by Windows Update itself.
- https://social.technet.microsoft.com/Forums/en-US/be35a9ee-a610-4fdc-bb6c-50b9f458d19a/huge-lcufolder-after-latest-cumulative-update-on-windows-10-1809?forum=win10itprosetup
- THIS MAYBE SHOULD BE ADDED TO WINAPP3.INI

### CODE REVIEW

**Comment by APMichael** [comment]
Thank you for the new ExludeKeys, but please use the correct syntax "\\|" and wildcards "\*".

For .LOG, .LOG1 and LOG2 you can use .LOG\*.

The variable %UserProfile% is used incorrectly because it points to the profile of the logged on user. You must use "%SystemDrive%\\Users\\\*". And instead of using Administrator, Default and Public, you can simply use a wildcard "\*".

A wildcard "\*" can also be used for all app packages: "%LocalAppData%\\Packages\\\*\\Settings\\|"

And please always use Winapp2ool > WinappDebug to make sure the syntax and sorting is correct before opening a new pull request. Thank you very much.

**Comment by decofona** [comment]
@APMichael You are right. But I'm not sure the excludekeys support wildcard * . Because when I tested out, it didn't. I run CCleaner 5.43.

**Comment by decofona** [comment]
I see, that in some entries this is done, but I tried myself, but excludekey didn't work. I will resolve the problems with winapp2.ini, but can you please tell me, how does excludekey and similar files like .log in one folder works.

Can I do something like this:


ExcludeKey1=FILE|%CommonAppData%\Microsoft\Search\Data\Applications\Windows|*.chk

or do I have to adress all files one by one?

**Comment by APMichael** [comment]
All entries are tested and work as expected. If you use only one file pattern per ExcludeKey, the wildcards will work. 

Your example: If you use wildcards, you should use PATH| instead of FILE|. And it is also important that you use the correct syntax "\\|".

ExcludeKey1=PATH|%CommonAppData%\\Microsoft\\Search\\Data\\Applications\\Windows\\|\*.chk

Please read the README.md for all necessary information.

An important note: If you specify different files using the separator ";", they always need to start with a wildcard. Without the wildcard, only the first pattern matches.

ExcludeKey1=PATH|%WinDir%\\|\*setup.log;\*install.log

**Comment by decofona** [comment]
Okay will checkout now.

**Comment by decofona** [comment]
Closed in favor of new entry.

**Pull request closed without merging**
