### PR TITLE
Cookies

### PR DESCRIPTION
**Pull request by APMichael**
- Added cookies cleaning back to Winapp2.ini. For people who always want to delete all cookies and make sure that all traces are really removed. (CCleaner does not remove the files themselves, but only tries to remove all traces from the databases stored in them.)

### CODE REVIEW

**Comment by mikhaelkh** [comment]
Since it overrides "Cookies to keep", maybe better to add it to Winapp3?

**Comment by mikhaelkh** [comment]
Since it overrides "Cookies to keep", maybe it's better to add it to Winapp3?

**Comment by APMichael** [comment]
As I wrote in the description, some people always want to remove all cookies at once (and the associated files). They do not want to use CCleaner's cookies management ("Cookies to Keep"). The entries are not dangerous, they do not break anything, they just remove all cookies. The warning allows the user to decide whether to enable the entries or not, as with other Winapp2.ini entries with a warning.

IMHO the entries do not make much sense as Winapp3.ini entries. Then we can leave them in the Removed entries.ini.

**Comment by mikhaelkh** [comment]
The danger is that it overrides internal CCleaner cookie settings.
IMHO when adding cookies to CCleaner whitelist, users should be sure that whilelisted cookies won't get erased, and such behavior should be considered dangerous.
It's possible that users won't pay attention to the warning, seeing "Cookies" and assuming that it will respect the whitelist.

**Comment by APMichael** [comment]
I fully understand your concerns. I used the same (your) arguments in the community forum.

But I also try to do justice to everyone's wishes. So I added a warning to the entries and opened a pull request.

Let's see what @MoscaDotTo (and other) opinions are.

**Comment by mikhaelkh** [comment]
I understand that Winapp3 is a lot less common. And the use of this entries would be that if I have both Chrome and Firefox, I can choose in which to ignore the whitelist.

Alternative would be to keep it in Winapp2, but under separate `Dangerous Chrome`/`Dangerous Firefox` categories.

**Comment by MoscaDotTo** [comment]
I think we generally like to avoid conflicting with CCleaner where we can. Perhaps trial it as is and if there are complaints we should consider moving it to the non-ccleaner file

**Comment by APMichael** [comment]
Thank you very much for your answer. Ok, I agree with that.

**Pull request merged**
