### PR TITLE
Add blacklist ini explanation

### LINKED ISSUE #904: HELP: Blacklist.ini format
Heya,

i cannot find any informations about the content of the blacklist format. Could you add some infos to the readme please?

### PR DESCRIPTION
**Pull request by reloxx13**
Closes #904

### CODE REVIEW

**Comment by APMichael** [comment]
I think this explanation is better placed in the ReadMe of [Winapp2ool/Trim](https://github.com/MoscaDotTo/Winapp2/tree/master/winapp2ool/modules/trim#readme) than in the ReadMe of the Winapp2.ini file description.

**Comment by jensdraht1999** [comment]
@reloxx13 any updates?

**Comment by reloxx13** [comment]
i disagree, trim readme is technical for devs and not for enduser. not my decision.

**Comment by jensdraht1999** [comment]
If custom.ini is used in the ReadMe of Winapp2.ini, we might use this also there, so reloxx13 could merge this PR as it is.

**Comment by MoscaDotTo** [comment]
More user-friendly ReadMes files for the modules would be great. Currently they mostly serve as a form of module documentation, in part because navigating the file structure to find them is a little user unfriendly. but there's no reason why the ReadMe for the modules themselves shouldn't contain instructions/elaboration. This is something we can definitely start work on after the next major winapp2ool update (many changes)

**Pull request closed without merging**
