### PR TITLE
SMPlayer

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by MoscaDotTo** [comment]
This looks fine to me. The SMPlayer2 directory is IIRC very old

**Comment by Tobias-B-Besemer** [comment]
SMPlayer2 directory doesn't exist anymore... (Guess since a long time...)

**Comment by APMichael** [comment]
Normally we don't remove keys from old versions, but i think we can make an exception here.

**Comment by Tobias-B-Besemer** [comment]
At the beginning I was thinking that this is a rule, that the file must exist, that the cleaner gets triggered...

**Comment by APMichael** [comment]
There are too much conflicts for merging. I will close this pull request and add all entries for you.

**Pull request closed without merging**
