### PR TITLE
Media Player Classic

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
I fix that...

**Comment by Tobias-B-Besemer** [comment]
I compared my entries with 'Removed entries.ini' & 'WinApp3.ini', they are all new!
I fixed the wildcard problem and a other bug I found, too.
I will upload a new version.

**Comment by APMichael** [comment]
Please read my comment again:
> Please keep in mind that Winapp2.ini is an extension for CCleaner. All your new Keys, except RegKey26, **are already covered by the CCleaner entry**. We can't add them.

BTW I don't know how you submit your changes/commits, but the "Files changed" view no longer works online and all your outdated commits are still shown here. I would suggest that you close all your pull requests and open new ones with the fixed changes. Please use one new commit (one new branch) for one pull request. Thank you very much.

**Comment by Tobias-B-Besemer** [comment]
K

**Comment by Tobias-B-Besemer** [comment]
One question: When my keys are not in WinApp2.ini, WinApp3.ini & in 'Removed entries.ini', how do I see that they are already hard-coded in CCleaner ???

2018-12-20 12_19_42-ccleaner - free for home use

**Comment by Tobias-B-Besemer** [comment]
I checked my fork and it's up to date...

2018-12-20 12_26_31-comparing tobias-b-besemer_master moscadotto_master tobias-b-besemer_winapp2

I did a misstake by the first patch and submitted it as master... Now I reverted the changes and so nothing is submit, but it seems as long I'm ahead of your master, the changes are everywhere shown in the history...

2018-12-20 12_27_39-comparing moscadotto_master tobias-b-besemer_master moscadotto_winapp2 - fir

**Comment by APMichael** [comment]
> One question: When my keys are not in WinApp2.ini, WinApp3.ini & in 'Removed entries.ini', how do I see that they are already hard-coded in CCleaner ???

I guess many people just run CCleaner and check if the file or registry key/value has been removed.

But there is a better way: Use this command `CCleaner.exe /export` and you will find the files "winapp.ini" and "winsys.ini" in the CCleaner directory.

**Pull request merged**
