### PR TITLE
Add Hacknet

### PR DESCRIPTION
**Pull request by TZocker**

### CODE REVIEW

**Comment by APMichael** [comment]
The "FileKey2=%LocalAppData%\\CrashDumps|\*.dmp" isn't necessary, because it's cleaned by CCleaner already (winsys.ini: Memory Dumps).

**Comment by APMichael** [comment]
Thanks for your reply. I'm not sure if this is a misunderstanding, but winsys.ini isn't a separate file, it's build into CCleaner (cleaning rule "Memory Dumps", in German "Speicherabbilder").

With the last big overhaul, we removed all duplicate FileKeys which were already covered by CCleaner itself (e.g. files in %Temp%). Therefore, it doesn't make much sense to start adding such FileKeys again.

Why should we start adding FileKeys for separated dump files, if CCleaner already removes them all together? (BTW dump files in that folder are usually created by Windows and not by the application itself.)

**Comment by APMichael** [comment]
@MoscaDotTo and @ROCKNROLLKID: What is your opinion?

**Comment by MoscaDotTo** [comment]
The crashdump folder is the usermode crash folder at the system level. Like you said, we don't include locations in %temp% because we can (safely) assume that anything running that supports winapp2.ini will also be able to clear that location and its contents (whose grouping is more accurately categorized as temporary files not associated with any program in particular) 

I don't think we need to include the crashdumps folder in individual entries for the same reason.

**Comment by APMichael** [comment]
@MoscaDotTo: Thanks for your reply.

@TZocker: I hope that's ok for you too.

**Comment by TZocker** [comment]
@APMichael sry i mix up winsys with winsys2 / winapp3 sry for it.

**Comment by APMichael** [comment]
Don't worry. Thanks for the update.

**Pull request merged**
