### PR TITLE
WIP: Update for Visual Studio 2017

### PR DESCRIPTION
**Pull request by magol**
Related to #94

Everything is not yet updated

# Left to do
- [ ] Make sure that all news in VS2017 is included
  - [X] Add cleaning of VS2017 installer
- [x] Make sure everything from VS2015 is included
- [ ] `MS Visual Studio Assembly Cache`: Update for VS2017
- [ ] `MS Visual Studio Dump Files`: Update for VS2017
- [X] `MS Visual Studio Backup`: Add VS2015 & VS2017
- [ ] `MS Visual Studio Dump Files`: Check if it still fits
- [ ] `MS Visual Studio Logs`: Check if something is missing
- [ ] `MS Visual Studio MRU`: Add VS2015 & VS2017 (see problem below)
- [ ] `MS Visual Studio Search History`: Check if it still fits
- [ ] `MS Visual Studio Website Cache`: Check if it still fits
- [X] `MS Visual Studio.NET 2003`: Delete or give better name
- [X] Add cleaning of NuGet packages
- [X] Add cleaning of other cache
- ~~`MS Visual Basic 2010 Express MRU`: Move to `MS Visual Studio MRU`?~~
- ~~`MS Visual Basic 2010 Express Search History`: Move to `MS Visual Studio Search History`?~~
- ~~`MS Visual C # 2010 Express MRU`: Move to `MS Visual Studio MRU`?~~
- ~~`MS Visual C ++ 2010 Express MRU`: Move to `MS Visual Studio MRU`?~~
- ~~`MS Visual C # 2010 Express Search History`: Move to `MS Visual Studio Search History`?~~
- ~~`MS Visual C ++ 2010 Express Search History`: Move to `MS Visual Studio Search History`?~~
- ~~`MS Visual Express 10 Backup`: Move to `MS Visual Studio Backup`~~

# Issues
 - [ ] How do I access the VS2017 registry?
 - [X] Do we need to support old Express versions? Yes, at least until Microsoft stops supporting them.

### CODE REVIEW

**Comment by TZocker** [comment]
Since when works wildspaces in Regkeys?

**Comment by magol** [comment]
@TZocker aaah, then I understand why there were so many "unnecessary" lines.  :tired_face:

**Comment by TZocker** [comment]
Hi,
I would stay the Express entries because this Special version is closed (now it is integrated as community edition in the normal VS)
but whats the diffrence between 
[MS Visual C# 2010 Express Search History*] and
[MS Visual C++ 2010 Express Search History*]

**Comment by magol** [comment]
@TZocker I agree we should keep them, at least until Microsoft stops supporting them.

The difference between `MS Visual C# 2010 Express Search History` and `MS Visual C++ 2010 Express Search History` is that they unfortunately use different registry keys

**Comment by TZocker** [comment]
Not by me???

http://s1.bild.me/bilder/110417/1139761vs2010.png

I think there are the same

**Comment by magol** [comment]
Ahh, I did not see that. It must be wrong. 
The Detect key for both of them is different

- HKCU\Software\Microsoft\VC**S**Express\10.0
- HKCU\Software\Microsoft\VCExpress\10.0

I guess that the keys for `MS Visual C# 2010 Express` must use `VCSExpress `instead of `VCExpress`. But to verify that, we must install it and test.

**Comment by ROCKNROLLKID** [comment]
This is looking good. I think we can also drop 2008 (9.0) as I think that one is also EOL, at least they put a notice in the documentation that they were no longer updating the documentations anymore.

Also, when you are done, do you mind also applying these to the non-CCleaner one here: https://github.com/MoscaDotTo/Winapp2/blob/master/Non-CCleaner/Winapp2.ini

**Comment by magol** [comment]
@ROCKNROLLKID  I checked [Microsoft's support site](https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20Visual%202008)  when the support expired for the different versions, and came to the following.

| Product name            | Version number | Mainstream Support End Date | Extended Support End Date | Service Pack Support End Date |
|-------------------------|----------------|-----------------------------|---------------------------|-------------------------------|
| ~~Visual Studio .NET 2003~~ | ~~7.1~~            | ~~2008-10-14~~                  | ~~2013-10-08~~                | ~~2007-10-09~~                    |
| ~~Visual Studio 2005~~      | ~~8.0~~            | ~~2011-12-04~~                  | ~~2016-12-04~~                | ~~2008-03-22~~                    |
| Visual Studio 2008      | 9.0            | ~~2013-07-01~~                  | 2018-04-10                | ~~2009-10-13~~                    |
| Visual Studio 2010      | 10.0           | ~~2015-07-14~~                  | 2020-07-14                | ~~2012-04-10~~                    |
| Visual Studio 2012      | 11.0           | 2018-04-02                  | 2023-01-10                | ~~2015-01-13~~                    |
| Visual Studio 2013      | 12.0           | ?                            |  ?                         |  ~~2016-10-11~~                             |
| Visual Studio 2015      | 14.0           | 2020-10-13                  | 2025-10-14                | 2017-10-10                    |
| Visual Studio 2017[61]  | 15.0           | 2022-04-12                  | 2027-04-13                |                               |


There is still limited support left for 2008 and 2010 for those who are willing to pay for it. But the question is whether it is enough to justify we have have support for it? I am hesitant that companies willing to pay for support also use CCleaner or similar products.

**Comment by ROCKNROLLKID** [comment]
I am not aware of any programs still using 2008, but I guess it doesn't hurt to keep them until Microsoft drops support. Keep up the good work!

**Comment by TZocker** [comment]
http://s1.bild.me/bilder/110417/3699722vcs2010ex.png

So i installed it and we can go on...

PLS can you update this tickets to the main file.

greets

**Comment by ROCKNROLLKID** [comment]
@magol  Are you still working on this? Otherwise I just merge and clean it up a bit now until someone else can pick up on this.

**Comment by magol** [comment]
Sorry, i do not have the time to finish this right now. Please merge this now, so maybe someone else can finish it later.

**Comment by TZocker** [comment]
This was lost:


23c5278

**Pull request merged**
