### PR TITLE
Changelog Full

### PR DESCRIPTION
**Pull request by winapp2**
Full Changlog. Closing other Pull Request.

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
Nice, but this was kind of unneeded. The change log is already on a GitHub page. You can just post the link in the README file.

**Comment by winapp2** [comment]
The changelog for the entries isn't here on github. But the changelog is on winapp2.com. 

But as you can imagine, we should really maintain the changelog here and close other ways (Website and forum) as much as possible. The changelog is the most important thing we will need here.

**Comment by ROCKNROLLKID** [comment]
I think you misunderstood what I mean. The changelog file is already on GitHub. There is no need to make another file for it. If you click on the changelog on the forums, it can see it directs you to GitHub page.

Not sure what he wants to do with the website. I think he might just keep it for a source and all.

The forums is part of Piriform, so he can't do anything with that.

**Comment by winapp2** [comment]
Can you please post the link of the changelog here in github. I really can't find it. @ROCKNROLLKID :+1:

**Comment by winapp2** [comment]
@ROCKNROLLKID I really can't find the changelog.

**Comment by ROCKNROLLKID** [comment]
The changelog is here and is auto updated when it gets edited: https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini

**Comment by winapp2** [comment]
This is just winapp2.ini, not the chnagelog.

**Comment by ROCKNROLLKID** [comment]
Sorry, I meant this link: http://www.winapp2.com/changes.txt

I suppose we could always move it over here, too. Perhaps it might be easier if it's here.

**Comment by winapp2** [comment]
I think we should upload the changes to here and Robert should link the file to this github, because development goes from here. After this pull request we should make a decision. 

Normal plain text or HTML format? 

If HTML format is editable and reforming it back to text is easy, I say we should take HTML.

**Comment by winapp2** [comment]
@ROCKNROLLKID I'll delete my Github.com account later. Please try to add PR's as fast as possible today. I just wanted to help this project a few days, now I have done the last steps.

**Pull request closed without merging**
