### PR TITLE
Update winapp2ool to 1.0 and introduce winapp2oolXP

### PR DESCRIPTION
**Pull request by MoscaDotTo**

### CODE REVIEW

**Comment by MoscaDotTo** [comment]
Looking for testers for this. Lots of things have changed. 

winapp3.ini support has been added which should address both 
#238 #237 

TrimXP will be deprecated with the release of winapp2oolXP, which should address 
#302 

#285 should be fixed. Please let me know 

I don't think much changed in terms of work towards #200 but at least the bug mentioned most recently on that thread was fixed.

Other changes include:

Offline mode: Not only should the app no longer crash when started offline, but it should both tell you, and allow you to use the local settings. 

Winapp2oolXP: As mentioned above, this version of winapp2ool has lower .NET requirements. This means some features like updating the application are disabled, but others like using online winapp2.ini files should work.

WinappDebug:

Alphabetization now properly respects numerical precednece. This might seem unintuitive in some spaces but allows ascending version numbers (the primary usecase) to properly sort. Some entries with numbers in their names (particularly those beginning with them) will move around in winapp2.ini as a result of this change.

FileKey optimization: 

The debugger can now attempt to merge multiple FileKeys into one. This setting is gated off by default and requires toggling in the advanced setting menu. 

Changing an advanced setting menu option no longer forces on auto correction

Trim:

Changed to a (hopefully) more reliable methodology of determining the Window version, which should also be much faster. The old method was slow for some reason (though accurate). Please let me know if you experience any errors with DetectOS defined keys (especially on Windows 8.1, but generally on anything older than Windows 10) 

Diff: 

The main diffing algorithm is no longer part of the iniFileHandler, which decouples iniFileHandler from winapp2fileHandler. yay!

Downloader: 

Added a new menu where you can download winapp3.ini from. Possible that additional files may be found here in the future? 

Copyright and licensing notices have been added to all the source files.

Most importantly(?)! Most (all? I hope! Exhausting...) Docstrings have been filled out. Great news for documentation and fantastic news for those who are trying to understand what it is winapp2ool is doing. 




Those are what spring to mind! Please give these a try and report back anything that jumps out as an error.

**Comment by APMichael** [comment]
Thank you very much for the big update. It looks good to me.

One little thing, WinappDebug shows following error with the file 'Removed entries.ini':

Line: 101 - Error: %EnvironmentVariables% must be surrounded on both sides by a single '%' character.
Key: Detect=HKCU\\Software\\Alcohol Soft\\Alcohol 120%

I think checking %EnvironmentVariables% is only needed for DetectFile and FileKey lines.

**Comment by MoscaDotTo** [comment]
> I think checking %EnvironmentVariables% is only needed for DetectFile and FileKey lines.

This is the intention :) Instances of single Detects were slipping through the cracks. V simple fix

**Comment by APMichael** [comment]
Thank you very much for update. It looks good to me.

I found a little problem: WinappDebug crashes if the file contains only one entry and nothing else. A workaround is to add a line with only one semicolon (;) at the beginning of the file.

Translated error message:
```
Untreated exception: System.NullReferenceException: The object reference was not defined for an object instance.
   at winapp2ool.winapp2handler.winapp2file..ctor(iniFile file)
   at winapp2ool.WinappDebug.debug(iniFile cfile)
   at winapp2ool.WinappDebug.initDebug()
   at winapp2ool.Winapp2ool.initModule(String name, Action callMenu, Action`1 handleInput, Boolean chkUpd)
   at winapp2ool.Winapp2ool.initModule(String name, Action callMenu, Action`1 handleInput, Boolean chkUpd)
   at winapp2ool.Winapp2ool.main()
```

**Comment by MoscaDotTo** [comment]
Agreed. It looks particularly strange when there is no file name (':')

**Comment by APMichael** [comment]
Would it be difficult to add a check for duplicate entry names to WinappDebug? I have just noticed that this is not yet detected.

**Comment by MoscaDotTo** [comment]
It used to be detected, this is a regression and I will fix it

**Comment by MoscaDotTo** [comment]
Just to clarify:

Duplicate entry names are detected by winapp2ool but only if they aren't an identical match to an existing entry. This is due to a limitation of Dictionaries (the underlying data structure for iniKey objects): the require unique "keys" and the entry names are the keys. 

A message prints informing the user that this is the case and that the entry cannot be processed until it has a unique name.

.... but it's impossible to read because of where it lies in the codepath, so I'm adding a prompt that'll ask the user for input before continuing.

**Comment by APMichael** [comment]
As long as you get any kind of feedback that there's a duplicate entry name, that's fine with me.

**Comment by APMichael** [comment]
I downloaded the latest build, but unfortunately duplicate entry names are still not detected. Only the number of entries is reduced like in the previous versions. 

I tested it with a small file and named two entries identically. Maybe I misunderstood something because you wrote "...but only if they aren't an identical match to an existing entry." But a duplicate entry name is always identical, right? If not, do you have a short example of which duplicate entry names are detected? Thank you very much.

**Comment by MoscaDotTo** [comment]
Entry names are case sensitive

image

here we see an exact match (prohibited by the inifile constructor for the reasons mentioned above)

If the case isn't matched, we must still consider it an error since CCleaner is not quite as adept at handling this case as we are, and the message is printed accordingly

image

**Comment by APMichael** [comment]
Thanks for your reply.

The second detection (case isn't matched) works. The output is exactly like the screenshot. The first detection (exact match) unfortunately doesn't work. WinappDebug doesn't stop and reports 0 errors.

Maybe I downloaded the wrong version? Your version shows v1.0, my version v1.0 beta. I tried the following two files:

https://github.com/MoscaDotTo/Winapp2/tree/c48d80781c5214ce19b550cd8ca94a860eaa2338/winapp2ool/bin/Debug
https://github.com/MoscaDotTo/Winapp2/tree/c48d80781c5214ce19b550cd8ca94a860eaa2338/winapp2ool/bin/Release

Anyway, it works with your version, so it should work with the final public release.

**Comment by MoscaDotTo** [comment]
Updated build should work

**Comment by APMichael** [comment]
I downloaded the following .exe:
https://github.com/MoscaDotTo/Winapp2/blob/c32a01840cfb9f0eab156c73c2b0bc1558175ade/winapp2ool/bin/Release/winapp2ool.exe
But it still isn't working.... Very strange?!

And unfortunately another bug occurs now: WinappDebug detects forward slashes / in Warning= lines as an error.

**Comment by MoscaDotTo** [comment]
Very strange that the duplicate check is not working on tour machine. I used @32a018 and it worked fine with the following snippet at the top of a freshly downloaded winapp2.ini:

```
; Version: 181220
; # of entries: 2,052
;
; Winapp2 is fully licensed under the CC-BY-SA-4.0 license agreement. Please refer to our license agreement before using Winapp2: https://github.com/MoscaDotTo/Winapp2/blob/master/License.md
; If you plan on modifying, distributing, and/or hosting Winapp2 for your own program or website, please ask first.
;
; You can get the latest Winapp2 here: https://github.com/MoscaDotTo/Winapp2
; Any contributions are appreciated. Please refer to our readme to learn to make your own entries here: https://github.com/MoscaDotTo/Winapp2/blob/master/README.md
; Is CCleaner taking too long to load with Winapp2? Then download our Winapp2ool and use the trim function to remove unneeded entries in Winapp2. https://github.com/MoscaDotTo/Winapp2/blob/master/Tools/beta/winapp2ool.exe
;
; Chrome/Chromium based browsers.

[Application Cache *]

[Application cache *]


[Application Cache *]
LangSecRef=3029
Detect1=HKCU\Software\7Star\7Star
Detect2=HKCU\Software\360Browser\Browser
Detect3=HKCU\Software\Amigo
Detect4=HKCU\Software\BraveSoftware\Brave-Browser
Detect5=HKCU\Software\CentBrowser
Detect6=HKCU\Software\ChromePlus
Detect7=HKCU\Software\Chromium\PreferenceMACs
Detect8=HKCU\Software\CocCoc\Browser
Detect9=HKCU\Software\Comodo\Dragon
Detect10=HKCU\Software\Coowon\Coowon
Detect11=HKCU\Software\Epic Privacy Browser
Detect12=HKCU\Software\Flock
Detect13=HKCU\Software\Opera Software
Detect14=HKCU\Software\RockMelt
Detect15=HKCU\Software\Slimjet
Detect16=HKCU\Software\Torch
Detect17=HKCU\Software\Vivaldi
Detect18=HKCU\Software\Yandex\YandexBrowser
DetectFile1=%AppData%\brave
DetectFile2=%LocalAppData%\Google\Chrome*
Default=False
FileKey1=%AppData%\brave\Application Cache|*.*|RECURSE
FileKey2=%AppData%\Opera Software\Opera*\Application Cache|*.*|RECURSE
FileKey3=%LocalAppData%\7Star\7Star\User Data\*\Application Cache|*.*|RECURSE
FileKey4=%LocalAppData%\360Browser\Browser\User Data\*\Application Cache|*.*|RECURSE
FileKey5=%LocalAppData%\Amigo\User Data\*\Application Cache|*.*|RECURSE
FileKey6=%LocalAppData%\BraveSoftware\Brave-Browser\User Data\*\Application Cache|*.*|RECURSE
FileKey7=%LocalAppData%\CentBrowser\User Data\*\Application Cache|*.*|RECURSE
FileKey8=%LocalAppData%\Chromium\User Data\*\Application Cache|*.*|RECURSE
FileKey9=%LocalAppData%\CocCoc\Browser\User Data\*\Application Cache|*.*|RECURSE
FileKey10=%LocalAppData%\Comodo\Dragon\User Data\*\Application Cache|*.*|RECURSE
FileKey11=%LocalAppData%\Coowon\Coowon\User Data\*\Application Cache|*.*|RECURSE
FileKey12=%LocalAppData%\Epic Privacy Browser\User Data\*\Application Cache|*.*|RECURSE
FileKey13=%LocalAppData%\Flock\User Data\*\Application Cache|*.*|RECURSE
FileKey14=%LocalAppData%\Google\Chrome*\User Data\*\Application Cache|*.*|RECURSE
FileKey15=%LocalAppData%\MapleStudio\ChromePlus\User Data\*\Application Cache|*.*|RECURSE
FileKey16=%LocalAppData%\RockMelt\User Data\*\Application Cache|*.*|RECURSE
FileKey17=%LocalAppData%\Slimjet\User Data\*\Application Cache|*.*|RECURSE
FileKey18=%LocalAppData%\Torch\User Data\*\Application Cache|*.*|RECURSE
FileKey19=%LocalAppData%\Vivaldi\User Data\*\Application Cache|*.*|RECURSE
FileKey20=%LocalAppData%\Yandex\YandexBrowser\User Data\*\Application Cache|*.*|RECURSE
```

output:
```
Error: Duplicate section name detected: [Application Cache *]
Line: 62
Duplicates the entry on line: 0
This section will be ignored until it is given a unique name.

Press enter to continue.

 ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
 ║                                          Beginning analysis of winapp2.ini                                         ║
 ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

Line: 13 - Error: Entry has no valid detection keys (Detect, DetectFile, DetectOS, SpecialDetect)
Entry Name: [Application Cache *]

Line: 13 - Error: Entry has no valid FileKeys or RegKeys
Entry Name: [Application Cache *]

Line: 13 - Error: Entry is missing a Default key
Entry Name: [Application Cache *]

Line: 15 - Error: Duplicate entry name detected
Entry Name: [Application cache *]

Line: 15 - Error: Entry has no valid detection keys (Detect, DetectFile, DetectOS, SpecialDetect)
Entry Name: [Application cache *]

Line: 15 - Error: Entry has no valid FileKeys or RegKeys
Entry Name: [Application cache *]

Line: 15 - Error: Entry is missing a Default key
Entry Name: [Application cache *]

Line: 4386 - Error: Forward slash (/) detected in lieu of blackslash (\).
Key: Warning=This possibly will reset default programs back to default on Windows 8/8.1.

Line: 5463 - Error: Forward slash (/) detected in lieu of blackslash (\).
Key: Warning=This will delete all saved SMART data for history/graph function.

Line: 18708 - Error: Forward slash (/) detected in lieu of blackslash (\).
Key: Warning=This cleans the Add/Remove Programs cache and will fix very large areas of black gaps in it. Using this will cause Add/Remove Programs to take a very long time to load since it will have to rebuild the cache.

Line: 13 - Error: Entry alphabetization
Application Cache * appears to be out of place
Current line: 13
Expected line: 15

Line: 15 - Error: Entry alphabetization
Application cache * appears to be out of place
Current line: 15
Expected line: 13

 ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
 ║                                          Completed analysis of winapp2.ini                                         ║
 ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
 ║ 12 possible errors were detected.                                                                                  ║
 ║ Number of entries: 2053                                                                                            ║
 ║                                                                                                                    ║
 ║ Press any key to return to the menu.                                                                               ║
 ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by APMichael** [comment]
Thank you for your reply.

I tried again: I downloaded the Winapp2.ini with Winapp2ools. Opened it with the latest Notepad++ and copied the 2 variants of the Application Cache from your snippet. Saved the file and started WinappDebug.

The output is identical with the exception that this did not happen:
````
Error: Duplicate section name detected: [Application Cache *]
Line: 62
Duplicates the entry on line: 0
This section will be ignored until it is given a unique name.

Press enter to continue.
````

**Comment by MoscaDotTo** [comment]
Diffing is broken for a variety of reasons, working on a fix..

**Comment by MoscaDotTo** [comment]
I think that is most/all of the 1.0 related bustage. Diff should be working properly now: it never properly handled any modified key checking other than FileKey, RegKey, and ExcludeKey (this was an oversight) but it should now handle all keytypes correctly

**Comment by APMichael** [comment]
I've tried Diff and everything looks good to me. It found and reported all changes. Thank you very much for your work.

(The only thing that still doesn't work on my system is the detection of the "duplicate section name", for whatever reason. I also tested different encodings (UTF-8/ANSI) and line ends (Unix/Windows), but the error message doesn't appear.)

**Comment by Dutchman101** [comment]
The winapp2ool.exe link contained in winapp2.ini is currently invalid, resulting in a Github 404.
Looks like the reason is a capital "T" in 'Tools' part of the link.

https://github.com/MoscaDotTo/Winapp2/blob/master/Tools/beta/winapp2ool.exe doesn't work
https://github.com/MoscaDotTo/Winapp2/blob/master/tools/beta/winapp2ool.exe works (although adding "?raw=true" at the ending will be useful other than fixing the link's validity, because it would then also insta-download the tool executable rather than showing the binary in repo only.

**Comment by APMichael** [comment]
Thank you very much for your hint!

I think we should change the URL to:
https://github.com/MoscaDotTo/Winapp2/tree/master/winapp2ool

**Comment by Dutchman101** [comment]
> Thank you very much for your hint!
> 
> I think we should change the URL to:
> https://github.com/MoscaDotTo/Winapp2/tree/master/winapp2ool

Just my humble opinion; if it's not a direct download link, you may want it to be a location where the main .exe is atleast listed. The XP version is in the directory you mentioned, but not the most widely used one (simply Winapp2ool.exe) which is in the Bin/Release folder.

The reason for both this and my earlier suggestion (to make it a insta-download link rather than github dir) is that I believe people reading the commented section in winapp2.ini and notice a tool such as Winapp2ool exists, want to easily get it without confusion or further searching.

**Comment by APMichael** [comment]
Ok, I changed the URL to a direct download link.
Thank you very much for your clarification.
Happy New Year.

**Pull request merged**
