### PR TITLE
XnView & XnView MP

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by APMichael** [comment]
Again, we always try to make universal entries that combine all different versions of an application. Please do not split existing entries. Thank you very much.

Please add the additional RegKeys to the existing entry and fix them, because wildcards * are not supported. And please check if you want to remove a Registry key (removes the entire key including all its values) or a value (removes only the specified value):

Registry key:
RegKey1=HKCU\Software\Tool\Recent

Registry value:
RegKey1=HKCU\Software\Tool\Recent|File1
(Requires the pipe | symbol before the value.)

**Comment by Tobias-B-Besemer** [comment]
XnView and XnView MP are software from the same company, but two completely different programs! They are even not on the same code base!

**Comment by Tobias-B-Besemer** [comment]
I will fix the patch...

**Comment by Tobias-B-Besemer** [comment]
OK, I searched for a press release about XnView MP, but can't find one... I even searched in the forum... https://newsgroup.xnview.com/index.php ...
'XnView Classic for Windows' is a Windows only, 32-bit application in version 2.46, while 'XnView MP' is a multi-platform application, also as 64-bit version available, and comes in version 0.92.
IMHO did someone a big mistake to mix them up...

**Comment by Tobias-B-Besemer** [comment]
Normally, IMHO, the entries should be called 'XnView Classic for Windows' & 'XnView MP', but I don't wanna mix to much up...

2018-12-19 10_08_39-xnview v2 46 en

**Comment by Tobias-B-Besemer** [comment]
I had a look into 'Removed entries.ini' and the entry 'XnView Extras' contain only keys from 'XnView Classic'... So a splitting in WinApp2.ini should IMHO at the moment no problem...

**Comment by APMichael** [comment]
Please accept the guidelines of the Winapp2.ini Community. We have many universal entries, for example the entry for Microsoft Office. The code base of Office 2003 is also very different from the code base of Office 2016 Click-to-Run.

**Comment by Tobias-B-Besemer** [comment]
OK, I pushed already, but will write them together again and make a new push.

**Comment by APMichael** [comment]
Thank you very much!

**Comment by APMichael** [comment]
There are too much conflicts for merging. I will close this pull request and add all entries for you.

**Pull request closed without merging**
