### PR TITLE
Vuze

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
K

**Comment by Tobias-B-Besemer** [comment]
'Vuze Dasu Reports' was already splited... So I let it splited...

**Comment by APMichael** [comment]
> 'Vuze Dasu Reports' was already splited...

The entry [Vuze Dasu Reports *] contains a warning. I guess the reports are generally not "crap".

**Comment by APMichael** [comment]
There are too much conflicts for merging. I will close this pull request and add all entries for you.

**Pull request closed without merging**
