### PR TITLE
Added removed entry from CCleaner v5.24

### PR DESCRIPTION
**Pull request by MoscaDotTo**
Added [Camtasia Studio 8*]

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
In https://github.com/MoscaDotTo/Winapp2/pulls/MoscaDotTo  you took out some entries from another rule, as well. Can you please make a entry in the removed entries and call it More, or if that already exists, then call it Extras.

**Comment by MoscaDotTo** [comment]
Will do - should we retroactively do this for all [More*] entries? Basically all of them are extensions of existing entries in winapp.ini, and over time a lot of pieces of them (and even entire entries) have been absorbed from winapp2 to winapp.

**Comment by ROCKNROLLKID** [comment]
I started collecting removed entries in October 2013. Ever since then, if a entry was partially deleted, like some FileKeys get removed due to being added to CCleaner, I would make a separate entry in the removed entries section and call it [More*], or if that name was already being used in Winapp2, then I would call it [Extras*].

I would like to go through the removed entries and see if any of them need updating, as most of them have been in there for years now and haven't been looked at by anyone since.

**Comment by MoscaDotTo** [comment]
The CCleaner methodology is what initially shaped the separate version numbers -> separate entry style choice, but I think merging multiple versions of the same application is likely just fine for most use cases.

**Pull request merged**
