### PR TITLE
None-support of program ini-files

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
Have here e.g. %AppData%\IrfanView\i_view32.ini and it seems I can't clean that. :-/

### CODE REVIEW

**Comment by APMichael** [comment]
Thank you for your contribution.

Since some of your .ini files will not be removed, this does not mean that we generally do not support .ini files. The "i_view32.ini" file stores your user settings, and user settings are not crap! CCleaner means Crap Cleaner and therefore we only remove crap. A note about .ini files in the Readme is not required.

And thanks for the hint about the misleading Readme. @MoscaDotTo has already started a revision of the Readme (#335). You can leave a comment there if you find something misleading.

**Comment by Tobias-B-Besemer** [comment]
I don't wanna delete i_view32.ini! I wanna delete a part of i_view32.ini! Not possible with WinApp2.ini.

**Comment by APMichael** [comment]
Ok, but this is a missing function of the used cleaner program and has nothing to do with the Winapp2.ini file itself. A note that you cannot do something what was never intended does not make much sense to me.

**Comment by MoscaDotTo** [comment]
Hi! 

Just to clarify, winapp2.ini is constrained to operations that are supported by its host programs, particularly CCleaner which is where the project began. 

winapp2ool has components that are able to modify ini files down to the key (though comments aren't currently supported) that would be able to perform this functionality, but as it stands right now, winapp2ool does not implement any functions on generically defined inifiles. 

The components that make up winapp2ool were designed an intention to one day be used for this (and other similar functions) so stay tuned on that front ;)

**Pull request closed without merging**
