### PR TITLE
Merge pull request#894from MoscaDotTo/master

### PR DESCRIPTION
**Pull request by MoscaDotTo**
this update focuses on reducing the winapp2.ini file size somewhat by removing entries for defunct online services and merging related entries together. I didn't do a full audit for every defunct service, just skimmed the file for some that were easily identified. I'm sure there are more. Likewise for entries that could be merged due to being highly related.

### CODE REVIEW

**Comment by MoscaDotTo** [comment]
This work is ongoing but I wanted to open this to comments

**Comment by APMichael** [comment]
Personally, I like it when the Winapp2.ini is cleaned up accordingly. 👍

(When merging entries, care would currently need to be taken to ensure that this does not lead to potential problems with the open pull request #893.)

**Comment by MoscaDotTo** [comment]
We can merge that pull request before this one, and any merge conflicts will make themselves known. At a glance, I didn't see any that should overlap.

**Comment by MoscaDotTo** [comment]
[Device Metadata Cache *]
LangSecRef=3025
DetectFile1=%CommonAppData%\Microsoft\Windows\DeviceMetadataCache
DetectFile2=%WinDir%\System32\config\systemprofile\AppData\Local\Microsoft\Device Metadata
FileKey1=%CommonAppData%\Microsoft\Windows\DeviceMetadataCache\dmrccache.bak|*.*|REMOVESELF
FileKey2=%WinDir%\System32\config\systemprofile\AppData\Local\Microsoft\Device Metadata\dmrccache\downloads|*.tmp

I think this entry could be merged into some other entry, perhaps Windows Subsystems? Moreover, this feature is available on windows 7 and has a different path for that which we should investigate

**Comment by MoscaDotTo** [comment]
```
[DirectShow Filter *]
LangSecRef=3025
Detect1=HKCU\Software\Microsoft\MPEG2Demultiplexer
Detect2=HKCU\Software\Microsoft\Multimedia\ActiveMovie
RegKey1=HKCU\Software\Microsoft\MPEG2Demultiplexer|WriteCaptureDir
RegKey2=HKCU\Software\Microsoft\MPEG2Demultiplexer|WriteCapturePath
RegKey3=HKCU\Software\Microsoft\Multimedia\ActiveMovie\Filter Cache
RegKey4=HKCU\Software\Microsoft\Multimedia\ActiveMovie\Filter Cache64
```
This is another candidate for merging into windows subsystems, or maybe we can create a new entry for windows "desktop technologies?" This is functionally part of win32

**Comment by APMichael** [comment]
I have merged the open pull requests so that the big overhaul can be done with the latest Winapp2.ini version. I hope the conflicts can be easily resolved.

> Is there a simple way to determine whether or not Store Apps still exist? ...

A search using the package name might work. Just execute the following link via "Run":

`ms-windows-store://pdp/?PFN=<package name>`
Example: `ms-windows-store://pdp/?PFN=Microsoft.People_8wekyb3d8bbwe`

Note: Unfortunately, Windows system apps cannot be found with it.

**Comment by MoscaDotTo** [comment]
conflicts with the most recent update have been resolved

**Comment by APMichael** [comment]
> conflicts with the most recent update have been resolved

Great! During a quick check, I noticed the following:

---

`[Opera Logs *]`
FileKey1 already covered by [Opera Bookmarks/Preferences Backup *].

Corrected:
```
[Opera Logs *]
LangSecRef=3027
Detect=HKCU\Software\Opera Software
FileKey1=%AppData%\Opera Software\Opera*|LOG;LOG.old|RECURSE
FileKey2=%LocalAppData%\Programs\Opera*|*.log|REMOVESELF
FileKey3=%ProgramFiles%\Opera*|debug.log
FileKey4=%ProgramFiles%\Opera*\assistant|*.log`
```

---

`[Ashampoo Snap *]`
DetectFile1 should be DetectFile.

Corrected:
```
[Ashampoo Snap *]
LangSecRef=3024
Detect1=HKCU\Software\Ashampoo\Ashampoo Snap 7
Detect2=HKCU\Software\Ashampoo\Ashampoo Snap 8
Detect3=HKCU\Software\Ashampoo\Ashampoo Snap 9
Detect4=HKCU\Software\Ashampoo\Ashampoo Snap 10
Detect5=HKCU\Software\Ashampoo\Ashampoo Snap 11
Detect6=HKCU\Software\Ashampoo\Ashampoo Snap 2017
Detect7=HKCU\Software\Ashampoo\Ashampoo Snap 2018
DetectFile=%ProgramFiles%\Ashampoo Snap*
FileKey1=%AppData%\Ashampoo|*.log;*.txt;*.xml|RECURSE
FileKey2=%LocalAppData%\Ashampoo\BaNT|*.*|RECURSE
FileKey3=%ProgramFiles%\Ashampoo\Ashampoo Snap*|_NLogMsg.txt
```

---

`[Serious Sam *]`
FileKey3-5 are duplicates of FileKey6-8.

Corrected:
```
[Serious Sam *]
Section=Games
Detect1=HKCU\Software\Valve\Steam\Apps\41000
Detect2=HKCU\Software\Valve\Steam\Apps\41010
Detect3=HKCU\Software\Valve\Steam\Apps\41014
Detect4=HKCU\Software\Valve\Steam\Apps\41050
Detect5=HKCU\Software\Valve\Steam\Apps\41060
Detect6=HKCU\Software\Valve\Steam\Apps\41070
Detect7=HKCU\Software\Valve\Steam\Apps\204340
Detect8=HKCU\Software\Valve\Steam\Apps\227780
Detect9=HKCU\Software\Valve\Steam\Apps\564310
DetectFile=%ProgramFiles%\Serious Sam*
FileKey1=%ProgramFiles%\Serious Sam*|*.log
FileKey2=%ProgramFiles%\Serious Sam*\Temp|*.*
FileKey3=%ProgramFiles%\Steam\steamApps\Common\Serious Sam*|*.log
FileKey4=%ProgramFiles%\Steam\steamApps\Common\Serious Sam*\Log|*.*|RECURSE
FileKey5=%ProgramFiles%\Steam\steamApps\Common\Serious Sam*\Temp|*.*
```

---

`[Zoom *]`
FileKey3 and 4 are duplicates. 

Corrected:
```
[Zoom *]
LangSecRef=3022
DetectFile=%AppData%\Zoom
FileKey1=%AppData%\Zoom|*.txt
FileKey2=%AppData%\Zoom Plugin\checkforupdate|*.msi
FileKey3=%AppData%\Zoom\data|*.tmp.db;*.tmp.enc.db;*.zmdownload;zmonitorlog.bin
FileKey4=%AppData%\Zoom\data|*-journal;*.db-shm;*.db-wal|RECURSE
FileKey5=%AppData%\Zoom\data\ConfAvatar|*.*
FileKey6=%AppData%\Zoom\data\WebviewCache|*.old;LOG|RECURSE
FileKey7=%AppData%\Zoom\data\WebviewCache\*\ZoomApps\*\CefWebView|Visited Links
FileKey8=%AppData%\Zoom\data\WebviewCache\*\ZoomApps\*\CefWebView\*Cache|*.*|RECURSE
FileKey9=%AppData%\Zoom\data\WebviewCache\*\ZoomApps\*\CefWebView\blob_storage|*.*|RECURSE
FileKey10=%AppData%\Zoom\data\WebviewCache\*\ZoomApps\*\CefWebView\Network|Network Persistent State
FileKey11=%AppData%\Zoom\Logs|*.*|RECURSE
FileKey12=%AppData%\Zoom\Reports|*.*
FileKey13=%AppData%\Zoom\ZoomDownload|*.exe;*.msi
```

---

`[WinZip ... *]`
The entries seem to be only partially merged - if merging was intended.

**Comment by MoscaDotTo** [comment]
I think there was some strangeness with line ending encoding on my end, some keys seem to have gotten broken in the conflict resolution process

**Comment by MoscaDotTo** [comment]
Perhaps we should consider retiring some of the chrome browser keys. I don't think  7star, ChromePlus/CoolNovo, Coowon, Flock, Rockmelt, Superbird, or Torch are still maintained

**Comment by MoscaDotTo** [comment]
I'm working on some upgrades to winapp2ool to accompany these and some future changes I want to make, namely extending some support towards determining if entries have been renamed or merged into other entries, here's a sample run. 

[diff.txt](https://github.com/MoscaDotTo/Winapp2/files/8953372/diff.txt)

best viewed with a monowidth font

**Comment by MoscaDotTo** [comment]
It's not perfect, fwiw. there are some changes that are still outside of its scope that im not certain I could meaningfully address, such as when an entry is merged into another in such a way that its keys arent simply placed into that entry but merged into existing keys with wildcards, winapp2ool will still detect the old version of the entry as having been removed rather thann merged. Still, this catches a pretty good chunk of this large changes very accurately and will probably fare better on more simple data sets in the future (ie updates to winapp2.ini that aren't a major refactor)

**Comment by MoscaDotTo** [comment]
diff
[diff.txt](https://github.com/MoscaDotTo/Winapp2/files/9023317/diff.txt)

Current output from Diff for this set of changes which is probably largely complete in terms of the major work here. I've done my best to make winapp2ool able to make sense of some of the changes but nevertheless some things will slip through the cracks (notably entries who were merged into other keys through use of wildcards instead of directly transplanting keys will register as removed/modified instead of merged/modified)

**Comment by MoscaDotTo** [comment]
I cannot find any reference to the registry keys referenced in Browser Exit Codes via google, beyond an old chromium bug report that said these keys were being created erroneously, any info on what this registry key is supposed to be?

**Comment by MoscaDotTo** [comment]
Most places where we use |*.*| (any file name with any extension), we might really mean |*| (any file) 

I don't want to unilaterally make any sweeping changes to cleaning rules but we might want to adopt this convention moving forward

**Comment by APMichael** [comment]
I have never tried it with a single asterisk \|\*\|, but if there is no difference to the previously used variant \|\*\.\*\|, then there is nothing against using the shortened variant \|\*\| in the future.

**Comment by MoscaDotTo** [comment]
recent diff: 
[diff.txt](https://github.com/MoscaDotTo/Winapp2/files/9786452/diff.txt)

**Comment by MoscaDotTo** [comment]
im merging this. the work isn't really "done" but I guess it never is and life similarly never gets less busy :) thanks for the patience

**Pull request merged**
