### PR TITLE
Update Winapp2.ini

### PR DESCRIPTION
**Pull request by novaceb881**
LOG can be found here:

https://github.com/MoscaDotTo/Winapp2/issues/419

And forget, that it will delete "default=true" also

### CODE REVIEW

**Comment by APMichael** [comment]
Thanks for the new and revised entries.

Please note the following:
- Please do not change the header text.
- Winapp2.ini still needs "Default=False" (until a new stable version of Winapp2ool is released).
- Detect does not need the "Wow6432Node" path (CCleaner always checks it).
- Please merge entries and FileKeys if possible.
- [Complete Internet Repair Logs *] is already covered by [Complete Internet Repair *].
- [Dell Backup and Recovery Logs *] is already covered by [Dell Logs *]
- We only support English program versions: [Internet Explorer *].
- [Tweaking.com - Windows Repair Backups *] should be Winapp3.ini.
- [Vodafone Database *] should be Winapp3.ini.
- [Winly Libary *] should be Winapp3.ini.

I uploaded a fixed version for you.

**Comment by novaceb881** [comment]
Hello,

Okay, the changes are very good. Can you please review and merge.

Also can you please add the entries mentioned also to Winapp3.ini?

Thanks.

**Comment by APMichael** [comment]
Thank you for your quick reply.

If there are no more comments in the next days, we will merge this pull-request.

Yes, no problem. I will try to review your Winapp3.ini changes tomorrow and add the entries mentioned here.

**Comment by novaceb881** [comment]
Hi,

also checked again something.

[Complete Internet Repair *]
LangSecRef=3024
DetectFile1=%ProgramFiles%\Rizonesoft\Complete Internet Repair\ComIntRep.exe
DetectFile2=%AppData%\Rizonesoft\ComIntRep
FileKey1=%AppData%\Rizonesoft\ComIntRep\Logging|*.*|RECURSE

We need to add Detect2, since if the software is uninstalled, it will not be recognized.
There might be people, that install this software to fix their internet and unistall it afterwards.

**Pull request merged**
