### PR TITLE
Update Winapp2.ini

### PR DESCRIPTION
**Pull request by TZocker**
add new entries for nvidia

### CODE REVIEW

**Comment by TZocker** [comment]
Discuss:

%CommonAppData%\NVIDIA Corporation\*|*.log;*.bak;*.stat

%CommonAppData%\NVIDIA Corporation\*|*.log;*.bak

%CommonAppData%\Nvidia\*|*.bak

would be a nice reduce of entries.

**Comment by ROCKNROLLKID** [comment]
You don't mind applying the changes to the non-ccleaner version, do you?

**Comment by TZocker** [comment]
Why you asking for it? 

I think the team (you) do it automatically on a periode time?
Perhabs per script who add the winapp2.ini with the removal linies ?

**Comment by TZocker** [comment]
Like this ?

`@echo off
:: Programms:
:: http://gnuwin32.sourceforge.net/packages/wget.htm
:: https://curl.haxx.se/download.html
:: http://waterlan.home.xs4all.nl/dos2unix.html

echo Download winapp2.ini from Github
ping /n 1 raw.githubusercontent.com
if errorlevel 1 goto NOC
echo online

del noncc-winapp2.ini

::curl.exe -o Winapp2.ini -A "Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3" -G "https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini"

wget.exe -c --output-document=winapp2.ini "http://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini"

unix2dos.exe winapp2.ini

wget.exe -c --output-document=Winapp2Removed.ini "goo.gl/oPQ1vj"

unix2dos.exe winapp2removed.ini

type *.ini >>noncc-winapp2.ini

del winapp2.ini
del winapp2removed.ini

goto end
:NOC
echo no connection

:end
`

**Pull request merged**
