### PR TITLE
Avira update

### PR DESCRIPTION
**Pull request by TZocker**
Add wildspace on some pc there are other file paths

### CODE REVIEW

**Comment by TZocker** [comment]
PLS also add 
Detect2=HKECU\SOFTWARE\Avira\Antivirus

to both entries i lost it sry

**Comment by TZocker** [comment]
sry lost 
Detect2=HKCU\SOFTWARE\Avira\Antivirus

**Comment by winapp2** [comment]
Please look my comment on your commit.

**Comment by ROCKNROLLKID** [comment]
I'll fix the Default=False myself. Everything else looks good.

**Comment by TZocker** [comment]
sry on my entrie i havent delet it sry 
my mistake

thx

**Pull request merged**
