### PR TITLE
Update winapp2.ini

### PR DESCRIPTION
**Pull request by MoscaDotTo**
community updates

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
Hi, two issues here.
- Slack is already in winapp.ini file as 'Slack' and updated entries are in https://github.com/MoscaDotTo/Winapp2/pull/816/files
- The #'s in 'Steam*' entries are meant for marking new entries, they need to be removed.

**Comment by MoscaDotTo** [comment]
> 
> 
> Hi, two issues here.
> 
>     * Slack is already in winapp.ini file as 'Slack' and updated entries are in [#816 (files)](https://github.com/MoscaDotTo/Winapp2/pull/816/files)
> 
>     * The #'s in 'Steam*' entries are meant for marking new entries, they need to be removed.

Thanks for pointing this out. The latest commit should resolve these issues

**Comment by FuccDucc** [comment]
I don't know why this is 'pending' and invisible until i log in myself, but here you go:
review

**Comment by APMichael** [comment]
Are you sure you downloaded the correct Winapp2.ini?
https://raw.githubusercontent.com/MoscaDotTo/Winapp2/9fe4c2ff93a8105f99a0059c083e0a7cc5756fbe/Winapp2.ini

Because for me the new entry is displayed in CCleaner:
grafik

**Comment by MoscaDotTo** [comment]
Works for me as well

**Comment by APMichael** [comment]
Thank you for the big Winapp2.ini update. 👍

Please do not forget to update the Non-CCleaner Winapp2.ini (merged Winapp2.ini + Removed entries.ini).

**Comment by MoscaDotTo** [comment]
Will get on that this afternoon hopefully :)

**Pull request merged**
