### PR TITLE
Add [AceStream*]

### PR DESCRIPTION
**Pull request by GoldMath**
Various cache files and trace cleaning for AceStream / Ace Player (P2P streaming application)

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
You have the entry in the wrong location. It is currently in the Chrome section. There are 3 sections on top, Chrome/Chromium, Firefox, and Thunderbird. If it doesn't belong to any of them, then it just goes with all the others in ABC format.

**Comment by GoldMath** [comment]
My bad, I will know next time! 
Fixed, ready to roll.

**Comment by MoscaDotTo** [comment]
nit: FileKey1 and 2 should be reversed (such that the folders ascend alphabetically)

**Comment by GoldMath** [comment]
Done

**Comment by ROCKNROLLKID** [comment]
Looks good.

**Pull request merged**
