### PR TITLE
Add MPC-BE entries

### PR DESCRIPTION
**Pull request by jmlntw**
Suggestion for [MPC-BE](https://sourceforge.net/projects/mpcbe/) entries (recent file list).

(Sorry for #176. I accidentally removed the branch so PR closed automatically. 🙇 )

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
Your last PR had 20 RegKeys, but this one only has 1. Where those other ones not necessary?

**Comment by MoscaDotTo** [comment]
Looks to me as though this regkey removes the key Recent File List instead of removing all of its individual subkeys. LGTM

**Comment by jmlntw** [comment]
If you click "Files -> Recent Files -> Clear list" in MPC-BE, it will delete the whole `Recent File List` key. So it's fine to just delete the key, instead of listing all values in that.

**Comment by APMichael** [comment]
This can be merged with the [Media Player Classic \*] entry:
...
Detect1=HKCU\Software\Gabest\Media Player Classic
Detect2=HKCU\Software\MPC-BE
Detect3=HKCU\Software\MPC-HC\MPC-HC
Default=False
FileKey1=%AppData%\Media Player Classic|\*.dmp
FileKey2=%AppData%\MPC-\*|\*.dmp
...
RegKey22=HKCU\Software\MPC-BE\Recent File List
...

I assume we can also replace the 21 RegKeys of MPC-HC with:
RegKey23=HKCU\Software\MPC-HC\MPC-HC\Recent File List

**Pull request merged**
