### PR TITLE
Added Non-CCleaner Winapp2 file

### PR DESCRIPTION
**Pull request by ROCKNROLLKID**
This is the Winapp2 file that contains all removed entries due to CCleaner. This is intended for BleachBit, System Ninja, and Avira System Speedup users only.

### CODE REVIEW

**Comment by winapp2** [comment]
I think we should manage this the other way. 

We should have three files :


Winapp2.ini for CCleaner
Removed Entries 
Winapp2.ini for other cleaners. 

Let's say after a month we have about 36 new changes. The changes will apply  to winapp2.ini for CCleaner as it was always. 

After that a bash script or whatever will take the removed entries from "Remove-entries.ini" and merge them to the "Winapp2.ini for other cleaners".

**Comment by winapp2** [comment]
This is much more easier to manage.

**Comment by ROCKNROLLKID** [comment]
That is what I plan on doing. I just want to double check that this is correct before merging to the main branch.

**Comment by winapp2** [comment]
Ah okay.. This is very good.

**Pull request merged**
