### PR TITLE
Refactor Winapp3 Part 1

### PR DESCRIPTION
**Pull request by ROCKNROLLKID**
I am making progress of a small refactor of Winapp3. This is a small PR and should be ready to merge as is. I took out .bak and .old as they are already covered in [Backup Files *] and .err as it is covered in [Error Log Files *] and added *.~?? as this was one in Wise 365 that we didn't have here.

Before I proceed on though, I wanted some opinions on something. Should we combine all the log file cleaning into one entry? Specifically the ones I am thinking we should combine are:

[Binary Performance Log Files *]

[Error Log Files *]

[Exchange Reserve Transaction Log Files *]

[Gather Log Files *]

[Registry Hive Log Files *]

[Registry Transaction Log Files *]

[Usual Log Files *]

I am also planning on moving all the .log, .dmp, .tmp, etc out of the useless file extensions entry and into another one, as these are not necessary "useless file extensions". I am also going to do some research and add more to this entry, as well.

### CODE REVIEW

**Comment by APMichael** [comment]
The pattern "\*.bak" should then also be taken from the ExcludeKeys. Or should the ExcludeKeys be moved to the entry [Backup Files \*]?

You could also take the pattern "\*.log?" from the FileKey, because this is more or less covered by the entries [Registry Hive Log Files \*] and [Usual Log Files \*].

With the ExcludeKeys the question arises whether these are useful or not. Each user has completely different programs installed, which we cannot possibly cover all in the ExcludeKeys. Shall we restrict them to Windows only? But Windows actually protects its important files itself, doesn't it?

Personally, I wouldn't mind combining the other log file entries.

**Comment by ROCKNROLLKID** [comment]
I moved the .bak and .old exclude keys to the backup entry.

I will be moving .log and other file extensions in the next PR.

I am not sure how useful these excludekeys are. Most of these entries are from 2 different winsys, one someone sent a pr from and another from 2012 from a forum user. Both were a giant mess and I cleaned them up to Winapp2 standards and left most of the useful ones while removing some obsolete ones.

**Comment by ROCKNROLLKID** [comment]
Do you think this could also be a good addition for Winappdebug, detecting if FileKeys/RegKeys/Excludekeys are the same with different entries? Like .bak and .old being in both Backup and Useless extensions entry? What do you think @MoscaDotTo

**Comment by APMichael** [comment]
Ok, thanks for your reply.

I moved some overlooked ExcludeKeys. I hope that's okay with you.

About WinappDebug: Each path-pattern combination would have to be checked against the entire file. I'm not sure if this is easy to do. But let's see what Robert means.

**Pull request merged**
