### PR TITLE
Add [Overwolf *]

### PR DESCRIPTION
**Pull request by GoldMath**
Cleaning rules for Overwolf, gaming companion App

### CODE REVIEW

**Comment by TZocker** [comment]
Hi it is possible to use.

+FileKey1=%LocalAppData%\Overwolf\*Cache|*.*

**Comment by APMichael** [comment]
@GoldMath: The "cache" folders get recreated on every application start. Therefore, REMOVESELF isn't really necessary. Can you please check, if the following version of the entry works for you also? Thanks!

[Overwolf \*]
LangSecRef=Games
Detect=HKCU\\Software\\Overwolf
Default=False
FileKey1=%LocalAppData%\\Overwolf\\\*Cache|\*.\*|RECURSE
FileKey2=%LocalAppData%\\Overwolf\\Crashes|\*.\*|REMOVESELF
FileKey3=%LocalAppData%\\Overwolf\\Log|\*.\*|RECURSE
FileKey4=%LocalAppData%\\Overwolf\\Store\\AppIcons|\*.\*
FileKey5=%LocalAppData%\\Overwolf\\temp|\*.\*

**Comment by GoldMath** [comment]
After further testing there is some cleaning disturbing the Apps in Overwolf. 

I need to test more before it's Pull my bad.

**Comment by APMichael** [comment]
Ok, thank you for your reply. We will wait for your revised entry.

**Comment by GoldMath** [comment]
Well, I don't know If my edit is correct but here the fixed code:

[Overwolf *]
LangSecRef=Games
DetectFile=%LocalAppData%\Overwolf
Default=False
FileKey1=%LocalAppData%\Overwolf\*Cache|*.*|RECURSE
FileKey2=%LocalAppData%\Overwolf\Crashes|*.*
FileKey3=%LocalAppData%\Overwolf\Log|*.*|RECURSE
FileKey4=%LocalAppData%\Overwolf\PackagesCache|*.*|REMOVESELF
FileKey5=%LocalAppData%\Overwolf\temp*|*.*
ExcludeKey1=PATH|%LocalAppData%\Overwolf\*Cache\Local Storage\|*.*
ExcludeKey2=PATH|%LocalAppData%\Overwolf\DockIconsCache\|*.*

**Comment by GoldMath** [comment]
Anyway there is still something who broke the Apps with this cleaning after specific testing, I will let the Pull on-hold..

**Comment by APMichael** [comment]
Ok, thanks for testing and your reply.

**Pull request closed without merging**
