### PR TITLE
Uploaded tools for working with winapp2.ini

### PR DESCRIPTION
**Pull request by ShaneGowland**
Including source code and a binary file.

### CODE REVIEW

**Comment by winapp2** [comment]
Can you build a program for finding temporary files. For example like the [Useless Entry 2.2] on winsys2.ini, which actually works only with CCleaner analyzing. Something like batch file or whatever. 

And do you plan to upload here trim.bat?

**Comment by ShaneGowland** [comment]
Trim.bat wasn't me; however the WinappParser (included in /Tools/) can output a trimmed winapp2.ini file - although it hasn't been updated since Windows 7. At some point I'll do a proper readme file for it.

**Comment by winapp2** [comment]
Perfect my friend.

**Comment by TZocker** [comment]
Can you add winsys2.ini
thx

**Comment by ROCKNROLLKID** [comment]
@Shane: "Finally, have you taken over winapp2.com, or is that still exclusively Robbie’s site?"

No, Robert just made me a maintainer, but he still owns this project. He just has much less time on his hands now, so he wanted some extra help. I am not sure, though, what he is going to do with his old website. By the way, I am saying this here because it wouldn't let me reply to the forum post anymore.

Ad for this pull request, I guess it's up to Robert if he wants to include these here. Looks alright to me, though.

**Comment by ShaneGowland** [comment]
No worries. 

(Btw, you can continue posting in the thread. I forgot that by making it an announcement I was also locking the thread)

**Pull request merged**
