### PR TITLE
Chrome / Opera

### PR DESCRIPTION
**Pull request by APMichael**
- Moved entries for the Chromium-based browser Opera to their own section. (Like the built-in entries of CCleaner.)

### CODE REVIEW

**Comment by MoscaDotTo** [comment]
Is this something we'd want in a top-level section in the file? winapp2ool can be easily modified to accommodate this

**Comment by APMichael** [comment]
Yes, a top-level section for Opera would be great. And if you're already making changes to it, you could also add a top-level section for the new Microsoft Edge. In this context we should also allow the use of LangSecRef 3005, because CCleaner will certainly use it for the upcoming Microsoft Edge as well. Thanks a lot!

**Comment by MoscaDotTo** [comment]
The latest Debug build on Branch1 has been updated to support these changes

**Comment by MoscaDotTo** [comment]
Chromium based Edge section follows Chromium based browsers and take anything with `LangSecRef=3005`. Opera section follows Thunderbird and will take anything with `LangSecRef=3027`

**Comment by earlmills** [comment]
Stop sending messages unsubscribe me

**Comment by APMichael** [comment]
> 
> 
> Chromium based Edge section follows Chromium based browsers and take anything with `LangSecRef=3005`. Opera section follows Thunderbird and will take anything with `LangSecRef=3027`

Wow, that was quick. 😃 Is it possible that "Opera" follows "Chromium based Edge" because "Opera" is also a Chromium based browser? Then we would have all Chromium based browsers together. And is it possible to use "Section=Microsoft Edge Insider" also for "Chromium based Edge", at least until the browser is officially released as non-beta?

Found some typos: There is an extra space between "detecting" and "invalid" in the description of scan option "13. Path Validity". A comma in the word "certain" of scan option "25. Invalid Values". And a missing letter "n" in the word "unneeded" of scan option 9 and 23.

And a crash when an equal sign (=) is missing in a Key.

**Comment by MoscaDotTo** [comment]
The crash was actually for any time there's an invalid key because I was mistakenly trying to assign keys to the error list while processing the error list, should be fixed now alongside the other things you mentioned

**Comment by APMichael** [comment]
Thank you very much for the new build. There was a little misunderstanding about "Section=Microsoft Edge Insider", sorry. I meant whether it is possible to use `LangSecRef=3005` and `Section=Microsoft Edge Insider` to find the entries that should be moved to the Microsoft Edge top-level section. This will also move the already existing entries for the Microsoft Edge Insider to the top-level section.

The crash is fixed, but now leaves the following: `DeleteMe=This key was not provided with a value and will be deleted. The user should never see this, if you do, please report it as a bug on GitHub`

**Comment by earlmills** [comment]
Please stop sending me emails

**Comment by MoscaDotTo** [comment]
@earlmills you'll need to click the unsubscribe button on the page or in the email, sorry.

**Comment by MoscaDotTo** [comment]
I created a new repair that will try to insert missing equals signs into keys that have a valid winapp2.ini command in them (ie. filekey2%programfiles%.. will become filekey2=%programfiles%...)

There's a small bug where DetectOS without an = will be improperly turned into Detect keys.

The other change (to grab both section and langsecref) is also in place, please test it out

**Comment by APMichael** [comment]
The latest build works perfectly (the top-level section and the new repair). 😃 Thanks a lot!

**Comment by APMichael** [comment]
Unfortunately, I found a bug: If you use WinappDebug with the file Winapp3.ini, it now deletes the top-level section "Potentially very long scan time (and also dangerous) entries" and all corresponding entries.

**Pull request merged**
