### PR TITLE
Updated Star Citizen entry

### PR DESCRIPTION
**Pull request by hvcrios**
-Fixed problem where the launcher would lose some settings (they save those in a log file.. go figure)
-Added a couple of cache folders for the launcher

### CODE REVIEW

**Comment by APMichael** [comment]
Thanks!

Are these two folders the only ones that have "Cache" in their names? 
```
FileKey4=%AppData%\rsilauncher\Cache|*.*
FileKey5=%AppData%\rsilauncher\GPUCache|*.*
```

If so, we could merge them:
```
FileKey4=%AppData%\rsilauncher\*Cache|*.*
```

**Comment by hvcrios** [comment]
Ah! yes indeed, didn't think of that

Should I change that and make another commit? (a bit new to this github thing)

**Comment by APMichael** [comment]
Thank you for your quick reply.

If you like. But I can also correct it when I merge the pull request.

**Comment by hvcrios** [comment]
> 
> 
> Thank you for your quick reply.
> 
> If you like. But I can also correct it when I merge the pull request.

Ah, alright then, you can go ahead and do it, I'll have to rebase my fork if I ever do more changes in the future anyway.

I'll keep the smarter use of wildcards in mind for any future contributions I make :P

Thanks.

**Pull request merged**
