### PR TITLE
Update Winapp2.ini

### PR DESCRIPTION
**Pull request by Koinonein**
Added some logs

### CODE REVIEW

**Comment by MoscaDotTo** [comment]
nit: could be 1 FileKey

FileKey21=%LocalAppData%\Koinonein BitTorrent Client*\Application|log.db 

other than that LGTM

**Comment by Koinonein** [comment]
Thanks, you know it looked like FileKey was a numbered list hence the 
21, would you mind making the change?

**Comment by MoscaDotTo** [comment]
Is Koinonein Bittorrent Client related to Chrome? If not, it'll need to be it's own entry. I overlooked that in my first review.

**Comment by Koinonein** [comment]
No its a separate application

**Comment by MoscaDotTo** [comment]
In that case you should create a new entry for it in the form

[Koinonein Bittorrent Client*]
LangSecRef=3022 
Detect=... and/or
DetectFile=... 
Default=False
FileKey1=%LocalAppData%\Koinonein BitTorrent Client*\Application|log.db

where Detect is a registry path that is unique to Koinonein or DetectFile is a unique file path. Multiples can be listed similarly to FileKeys by adding ascending numbers to the end

**Comment by MoscaDotTo** [comment]
In that case you should create a new entry for it in the form

[Koinonein Bittorrent Client*]
LangSecRef=3022 
Detect=... and/or
DetectFile=... 
Default=False
FileKey1=%LocalAppData%\Koinonein BitTorrent Client*\Application|log.db

where Detect is a registry path that is unique to Koinonein or DetectFile is a unique file path. Multiples can be listed similarly to FileKeys by adding ascending numbers to the end

**Comment by Koinonein** [comment]
You know with the changes done what if both the 32 and 64 versions are installed? looks like `%ProgramFiles%` will be either 64 bit on 64 bit CCleaner and 32 bit on 32bit CCleaner rather than 64bit CCleaner picking up both?

**Comment by ROCKNROLLKID** [comment]
It should detect both.

You still don't have the entry in the right spot. Please note that the top of Winapp2 has 3 sections now: 1 for Chrome/Chromium, 1 for Firefox and 1 for Thunderbird. You currently have your entry in the Firefox section, and the section under Firefox is thunderbird. Please put this in the generally list under the Thunderbird section in ABC order.

**Pull request merged**
