### PR TITLE
Winsys2.ini

### PR DESCRIPTION
**Pull request by winapp2**
This is for extreme entries, which should only be used from advanced members, not kiddys.

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
It's not bad, but I don't think we should re-add entries if you do not know why they were deleted in the first place. Some of those looks like they may break some programs.

**Comment by winapp2** [comment]
Yeah, this file will be separated to two files. One for extreme dangerous entries and one for documentation stuff. Please be patient a little bit more, you will understand what I intend later.

**Comment by TZocker** [comment]
we have to comit out all info lines and also put a warning in each entrie...

**Comment by winapp2** [comment]
Yeah I'm looking again later.

**Comment by winapp2** [comment]
other files sent. closing this.

**Pull request closed without merging**
