### PR TITLE
Clears Dropbox Update Logs

### PR DESCRIPTION
**Pull request by zero77**

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
Please remove C:\ from the FileKey and switch %ProgramData% to %CommonAppData%.

Also organize it in ABC order, too.

Thank you.

**Comment by zero77** [comment]
I have just realised that FileKey5 covers it.
Also, how can you find out what the correct LangSecRef= is.

**Comment by ROCKNROLLKID** [comment]
You may view that on the first post here: https://forum.piriform.com/topic/32310-winapp2ini-additions/?page=1

Yes, at a second look, FileKey 5 already covers this.

**Comment by zero77** [comment]
Thanks

**Comment by zero77** [comment]
This is very helpful, it may be worth adding it to the wiki or readme.

**Pull request closed without merging**
