### PR TITLE
Update winapp2ool

### PR DESCRIPTION
**Pull request by MoscaDotTo**
I had some time to work on winapp2ool this weekend, but the changes I made are many and largely untested so I don't want to push this to master just yet. Most of the changes are a mild refactor of how the menu system works to make it more robust, some changes to how file information is parameterized, stored in memory, and used, and exposing more portions of modules to be configurable.

Changes include but may not be limited to: 
Refactored most modules to expose many of their existing settings (and some new ones*) in the menu. Menus will also now display file paths (where ..\ means the current directory) for target files. 

Most places where you might have seen double headers at the top of the menu have been replaced with a single header. This is part of a larger menu code structuring change to reduce the amount and specificity of code required to output information to the menu.

Menus have been restructured to allow full configuration of a tool's run parameters before actually running the module. This is mostly a code structuring change, but users will notice that input isn't requested as often once a modules Run command is invoked.

Menus are also now responsive, so toggling some options will disable others, and the menu number ordering will reflect this. 

Modules now use a common function to toggle options on/off or to change file parameters. This is a code structure change but will make adding future items to menus much simpler. 

Some additional menu changes have been made to automatically generate the proper spacing for numbered menu items and their description. This work isn't done yet but is mostly complete. Not a user facing change. 

Modules now parameterize file location information in the form of a small object. This is entirely a code structuring change that the user wont see, but makes configuring files and the code associated with handling file parameters in general much simpler. 

Commandline Handling has been made more sane, but as of this pull request I have not tested it yet. Changes there include a simplified system of giving file parameters (no more per-module file parameters, any files being called are declared when the application starts and any unneeded file parameters will be ignored by the module - I will likely provide more information on the open bug for commandline args) 

Modules now offer an option to reset their settings to the default state if you change any of them. 

*Options changes:

CCiniDebug now gives the user an option for each step of its operations; the user can choose individually whether to prune stale winapp2.ini entries, sort, or save the changes ccinidebug makes (further optionally to a file that is not ccleaner.ini). Additionally, users can choose new names or locations for ccleaner.ini and winapp2.ini 

Trim now lets you choose a winapp2.ini and optionally a separate save location for the trimmed output. The options to run and download have instead been replaced with toggles for the two different download options. 

Merge will not run unless you specify a file to merge with winapp2.ini from the menu in some manner. The menu options to run with Removed Entries.ini or Custom.ini have been changed to toggles, and the location of winapp2.ini, the merge file (if you should wish to merge a file not named removed entries.ini or custom.ini) and the output file (should you wish not to overwrite your winapp2.ini) are all configurable. 

Diff is largely unchanged yet. Most likely in the next update, the download options will be toggles and the older/newer file setting will be done from the menu. 

WinappDebug can now have its winapp2.ini location or name changed, and save to a different file.

There might be more. There also might be bugs, 'cause I haven't thoroughly tested these changes just yet. Please give this version a try and report any problems on this bug

### CODE REVIEW

**Comment by APMichael** [comment]
Thanks for the new release. I like the new "find duplicate parameter" option of WinappDebug. But it finds too much duplicate paramters, e.g.:

FileKey1=%ProgramFiles%\Steam\steamapps|\*.mdmp;\*.tmp;\*.dmp;\*.icns;.DS_Store;logfile.\*;\*.log;text.txt;\*log.txt;log\*.txt|RECURSE
Error: log\*.txt

Those two parameters should be duplicates: "\*log.txt" and "log\*.txt". That would be correct only for a file named "log.txt" (without any other characters). But parameter one should match all files with "log" at the end of the file name and parameter two should match all files with "log" at the begin of the file name. Therefore, "\*log.txt" could not match "logABC.txt" and "log\*.txt" could not match "ABClog.txt".

Changing the parameter to "\*log\*.txt" would not be correct also, because "log" is allowed everywhere then.

**Comment by MoscaDotTo** [comment]
Yes, the duplicate parameter checker still has a few quirks. The basic premise of why it detects things like *log.txt and log*.txt as being the same boils down to the string matching technique I'm using. The part that is firing incorrectly was meant to be disabled in this build and will probably be disabled in the next commit fully.

**Comment by APMichael** [comment]
Ok, thank you very much for the clarification. It is a great idea anyway.

**Comment by MoscaDotTo** [comment]
image

:)

**Comment by MoscaDotTo** [comment]
Here's a new update, please check it for bugs if you wouldn't mind as it involves quite a lot of code rewriting and functionality changes. 

Probably most importantly, #281 is fixed by this. 

changes by module (since the above commit): 

winapp2ool.vb:

- Main now prints a message if your .NET Framework isn't v4.6 or higher 
Some new quick settings are available alongside updates, including:
winapp2.ini -
- Update: downloads the latest winapp2.ini to the current directory (ccleaner version only for now)
- Update & Trim: Same as above but also trims the file
- Show update diff: Shows the diff between your local file and the version on GitHub 

winapp2ool - 
- Update: Will download and automatically update winapp2ool.exe, leaving the old version as a .bak in the current directory 

CCiniDebug.vb:
- No longer will run if you disable all three options (sort, prune, save). Instead displays a prompt instructing you to select at least one

Diff.vb:
- Module settings all moved into the menu 
- Module will not run if you do not select a file against which to diff your local copy
- Now prints a verbose changelog explaining which keys in particular have been added/removed/modified. For modified keys, it shows both the old and new version.

Downloader.vb:
- Now includes an autoupdate functionality that can be used to update winapp2ool.exe in place
- Modified the downloader code to sometimes not require a prompt for overwriting a file (most likely a change that will be needed for automating actions through the commandline) 

MenuMaker: 
- MenuMaker has taken on a more direct role in handling the menus for all modules. Most modules previously did some portion of their menu management themselves (including hardcoded numbers and in the previous version of 0.85, hardcoded number calculations). Most/all of this functionality has been removed from the individual modules and replaced by new functions in the menumaker, who now also handles numbering menu options. 
- getMenuItemNumber now lives here instead of winapp2ool.vb

Trim.vb:
- Correctly expand wildcards in DetectFile paths and don't erroneously trim entries with them when they should return true

WinappDebug.vb:
- Individual toggling of various scantypes and their respective repairs 
- IniKeys with no valid data in their value (ExampleKey=) will now be detected and deleted as errors without crashing the module
- Changed the alphabetization checker to be more accurately aware of which specific lines are out of place. This should fix the problem where several out of place lines or entry names would cause a tremendous list of alphabetization errors
- Removed attempted string matching for wildcards in filekey parameters for duplicate detection (for now). Wholsesale duplicates will still be detected and removed appropriately. 
- Converted some chained conditionals for string matching to Regex matches
- Added optimization (disabled by default) checks; enabling this option will scan the file for filekeys or excludekeys that can be potentially merged into single parameterizations. It's rather basic and non-aggressive in these attempts right now. 

CommandLineHandler.vb:
- Restructured much of the code to be much simpler and more easily extendible. I didn't test whether or not the new format for the commandlinehandler works or not yet but it should, as it uses the same underlying command path as other parts of the program that do work. Feel free to test

iniFileHandler.vb:
- iFileHandlr class that was supporting file parametization has been removed and its functionality merged into the inifile class
- FileChooser/DirChooser have had their menus redesigned and configured to follow the same format as the other menus in the program
- iniSection compareTo functionality has been modified to output the difference between keys if there are any 
- Some helper functions have been added to simplify querying certain aspects of a key's value 
- inikeys with no value now get labeled DELETEME

winapp2handler.vb:
- winapp2string has been updated with our new headers for winapp2.ini & non-ccleaner version 

I think that's about the gist of it! I may have missed some stuff, I haven't been keeping a list.

**Comment by ROCKNROLLKID** [comment]
Does the automatic updater for Winapp2ool automatically download when Winapp2ool updates, as I do not see a toggle or anything for it?

**Comment by MoscaDotTo** [comment]
There will be prompts on the main menu when updates are available for the tool or winapp2.ini.

Otherwise, simply selecting winapp2ool.exe in the downloads menu without changing the download directory (which now defaults to the same as the current folder instead of ../winapp2ool downloads/) will initiate the autoupdate process. 

Running this right now will likely downgrade your version to 0.8beta since it fetches the latest version from master and this build is not there yet.

**Comment by MoscaDotTo** [comment]
image

image

**Comment by MoscaDotTo** [comment]
Looks like nothing major has cropped up so I'll merge this.

**Pull request merged**
